Repository Louie-03/sidedish, pull requests merged in 2022-04, with the labels that each got.

#2 [공통] Issues, PR templates 와 프로젝트 소개 README.md 추가
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: docs, common, feat

#16 [FE] MealContainer 레이아웃 작성
  FE/.gitignore
  FE/package-lock.json
  FE/package.json
  FE/src/App.jsx
  FE/src/MealContainer.jsx
Labels: feat, FE

#18 [FE] BestMealContainer 레이아웃 작성
  FE/.prettierrc
  FE/package-lock.json
  FE/src/App.jsx
  FE/src/BestMealCard.jsx
  FE/src/BestMealContainer.jsx
  FE/src/index.js
Labels: feat, FE

#20 [FE] components단위로 파일 분리
  FE/src/App.jsx
  FE/src/MealContainer.jsx
  FE/src/components/BestMealCard.jsx
  FE/src/components/BestMealContainer.jsx
  FE/src/components/Loader.jsx
  FE/src/components/MealCard.jsx
  FE/src/components/MealContainer.jsx
  FE/src/contant.js
Labels: refactor, FE

#21 [FE] 페어 리팩토링
  FE/.gitignore
  FE/jsconfig.json
  FE/src/App.jsx
  FE/src/components/BestMealCard/index.jsx
  FE/src/components/BestMealContainer/index.jsx
  FE/src/components/Loader/index.jsx
  FE/src/components/MealCard/index.jsx
  FE/src/components/MealContainer/index.jsx
  FE/src/constant/index.js
  FE/src/contant.js
  FE/src/index.js
  FE/src/util/index.js
Labels: refactor, FE

#22 [BE] 특정 음식 타입 조회 기능
  BE/src/main/java/sidedish/com/controller/ProductsController.java
  BE/src/main/java/sidedish/com/controller/ProductsDtoMapper.java
  BE/src/main/java/sidedish/com/controller/model/ProductMealTypeResponse.java
  BE/src/main/java/sidedish/com/domain/DiscountPolicy.java
  BE/src/main/java/sidedish/com/domain/Image.java
  BE/src/main/java/sidedish/com/domain/Product.java
  BE/src/main/java/sidedish/com/exception/NoSuchProductsException.java
  BE/src/main/java/sidedish/com/repository/DiscountPolicyRepository.java
  BE/src/main/java/sidedish/com/repository/DomainEntityMapper.java
  BE/src/main/java/sidedish/com/repository/ProductsRepository.java
  BE/src/main/java/sidedish/com/repository/entity/DiscountPolicyEntity.java
  BE/src/main/java/sidedish/com/repository/entity/ImageEntity.java
  BE/src/main/java/sidedish/com/repository/entity/ProductEntity.java
  BE/src/main/java/sidedish/com/service/ProductsService.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/application.yml
  BE/src/main/resources/db/data.sql
  BE/src/main/resources/db/schema.sql
  BE/src/test/java/sidedish/com/ComApplicationTests.java
  BE/src/test/java/sidedish/com/acceptancetest/ProductsAcceptanceTest.java
  BE/src/test/java/sidedish/com/controller/ProductsControllerTest.java
  BE/src/test/java/sidedish/com/domain/ProductTest.java
  BE/src/test/java/sidedish/com/repository/ProductsRepositoryTest.java
  BE/src/test/resources/application.yml
  BE/src/test/resources/testdb/data.sql
  BE/src/test/resources/testdb/schema.sql
Labels: feat, BE

#27 [BE] 특정 id의 음식 조회 기능
  BE/src/main/java/sidedish/com/controller/ProductsController.java
  BE/src/main/java/sidedish/com/controller/ProductsDtoMapper.java
  BE/src/main/java/sidedish/com/controller/model/ProductDetailTypeResponse.java
  BE/src/main/java/sidedish/com/domain/DeliveryPolicy.java
  BE/src/main/java/sidedish/com/domain/Product.java
  BE/src/main/java/sidedish/com/repository/DeliveryPolicyRepository.java
  BE/src/main/java/sidedish/com/repository/DomainEntityMapper.java
  BE/src/main/java/sidedish/com/repository/ProductsRepository.java
  BE/src/main/java/sidedish/com/repository/entity/DeliveryPolicyEntity.java
  BE/src/main/java/sidedish/com/repository/entity/ProductEntity.java
  BE/src/main/java/sidedish/com/service/ProductsService.java
  BE/src/main/resources/db/data.sql
  BE/src/main/resources/db/schema.sql
  BE/src/test/java/sidedish/com/acceptancetest/ProductsAcceptanceTest.java
  BE/src/test/java/sidedish/com/controller/ProductsControllerTest.java
  BE/src/test/java/sidedish/com/domain/ProductTest.java
  BE/src/test/java/sidedish/com/repository/DeliveryPolicyRepositoryTest.java
  BE/src/test/java/sidedish/com/repository/ProductsRepositoryTest.java
  BE/src/test/resources/testdb/data.sql
  BE/src/test/resources/testdb/schema.sql
Labels: feat, BE

#31 [BE] 추천 음식 조회 기능
  BE/src/main/java/sidedish/com/controller/ProductsController.java
  BE/src/main/java/sidedish/com/controller/ProductsDtoMapper.java
  BE/src/main/java/sidedish/com/repository/ProductsRepository.java
  BE/src/main/java/sidedish/com/service/ProductsService.java
  BE/src/test/java/sidedish/com/controller/ProductsControllerTest.java
Labels: feat, BE

#36 [BE] 특정 카테고리의 베스트 음식 조회 기능 구현
  BE/src/main/java/sidedish/com/controller/ProductsController.java
  BE/src/main/java/sidedish/com/domain/DiscountPolicy.java
  BE/src/main/java/sidedish/com/repository/ProductsRepository.java
  BE/src/main/java/sidedish/com/repository/entity/DiscountPolicyEntity.java
  BE/src/main/java/sidedish/com/service/ProductsService.java
  BE/src/test/java/sidedish/com/acceptancetest/ProductsAcceptanceTest.java
  BE/src/test/java/sidedish/com/controller/ProductsControllerTest.java
  BE/src/test/java/sidedish/com/repository/ProductsRepositoryTest.java
Labels: feat, BE

#38 [BE] 배포/개발 환경 application 분리
  BE/src/main/resources/application-dev.yml
  BE/src/main/resources/application-prod.yml
  BE/src/main/resources/application.yml
Labels: BE, Depoly

#39 [FE] 일반 Meal 컴포넌트 UI 구현
  FE/.env
  FE/.gitignore
  FE/src/App.jsx
  FE/src/assets/angle-left.svg
  FE/src/assets/angle-right.svg
  FE/src/components/BestMealContainer/index.jsx
  FE/src/components/Carousel/index.jsx
  FE/src/components/Carousel/style.js
  FE/src/components/MealCard/index.jsx
  FE/src/components/MealCard/style.js
  FE/src/components/MealContainer/index.jsx
  FE/src/components/MealContainer/style.js
  FE/src/constants/index.js
Labels: FE

#40 [FE] Best 컴포넌트 구현
  FE/src/components/BestMealCard/index.jsx
  FE/src/components/BestMealCard/style.js
  FE/src/components/BestMealContainer/index.jsx
  FE/src/components/BestMealContainer/style.js
Labels: feat, FE

#41 [BE] CORS 기능 추가 (시스템 환경변수 활용)
  BE/src/main/java/sidedish/com/config/WebConfig.java
  BE/src/main/resources/application-prod.yml
Labels: feat, BE, Depoly

#43 [BE] 특정 상품 주문 기능 구현
  BE/src/main/java/sidedish/com/controller/DomainDtoMapper.java
  BE/src/main/java/sidedish/com/controller/OrderController.java
  BE/src/main/java/sidedish/com/controller/model/OrderSaveRequest.java
  BE/src/main/java/sidedish/com/controller/model/OrderSaveResponse.java
  BE/src/main/java/sidedish/com/domain/DeliveryPolicy.java
  BE/src/main/java/sidedish/com/domain/DiscountPolicy.java
  BE/src/main/java/sidedish/com/domain/Image.java
  BE/src/main/java/sidedish/com/domain/Order.java
  BE/src/main/java/sidedish/com/domain/Product.java
  BE/src/main/java/sidedish/com/exception/NotEnoughStockQuantityException.java
  BE/src/main/java/sidedish/com/repository/DomainEntityMapper.java
  BE/src/main/java/sidedish/com/repository/OrderRepository.java
  BE/src/main/java/sidedish/com/repository/ProductsRepository.java
  BE/src/main/java/sidedish/com/repository/entity/OrderEntity.java
  BE/src/main/java/sidedish/com/repository/entity/ProductEntity.java
  BE/src/main/java/sidedish/com/service/OrderService.java
  BE/src/main/java/sidedish/com/service/ProductsService.java
  BE/src/main/resources/db/data.sql
  BE/src/main/resources/db/schema.sql
  BE/src/test/java/sidedish/com/controller/OrderControllerTest.java
  BE/src/test/java/sidedish/com/controller/ProductsControllerTest.java
  BE/src/test/java/sidedish/com/domain/ProductTest.java
  BE/src/test/resources/testdb/data.sql
  BE/src/test/resources/testdb/schema.sql
Labels: feat, BE

#48 [FE] 캐러셀 디자인, getCarouselDesign()
  FE/src/App.jsx
  FE/src/components/Carousel/index.jsx
  FE/src/components/Carousel/style.js
  FE/src/components/Main/index.jsx
  FE/src/components/MealCard/index.jsx
  FE/src/components/MealCard/style.js
  FE/src/components/MealContainer/style.js
  FE/src/constants/index.js
  FE/src/styles/theme.js
Labels: FE

#49 [FE] GNB Design 구현
  FE/src/App.jsx
  FE/src/assets/logo.svg
  FE/src/components/BestMealContainer/style.js
  FE/src/components/Carousel/index.jsx
  FE/src/components/Carousel/style.js
  FE/src/components/Header/index.jsx
  FE/src/components/Header/style.js
  FE/src/styles/GlobalStyle.jsx
Labels: feat, FE

#50 [FE] BestMealCard 컴포넌트와 MealCard 컴포넌트 통합
  FE/src/App.jsx
  FE/src/Pages/Main/index.jsx
  FE/src/Pages/Main/style.js
  FE/src/assets/angle-left.svg
  FE/src/assets/angle-right.svg
  FE/src/components/BestMealCard/index.jsx
  FE/src/components/BestMealCard/style.js
  FE/src/components/BestMealContainer/index.jsx
  FE/src/components/BestMealContainer/style.js
  FE/src/components/Carousel/index.jsx
  FE/src/components/Carousel/style.js
  FE/src/components/Loader/index.jsx
  FE/src/components/MealCard/index.jsx
  FE/src/components/MealCard/style.js
  FE/src/components/MealContainer/index.jsx
  FE/src/constants/index.js
  FE/src/styles/theme.js
  FE/src/utils/index.js
Labels: feat, FE

#53 [BE] 도메인 설정으로 CORS 문제 해결
  BE/src/main/java/sidedish/com/config/WebConfig.java
Labels: fix, BE

#55 [BE] 도메인 객체의 불필요한 id 필드 제거
  BE/src/main/java/sidedish/com/domain/DeliveryPolicy.java
  BE/src/main/java/sidedish/com/domain/DiscountPolicy.java
  BE/src/main/java/sidedish/com/domain/Image.java
  BE/src/main/java/sidedish/com/repository/DomainEntityMapper.java
  BE/src/test/java/sidedish/com/controller/ProductsControllerTest.java
  BE/src/test/java/sidedish/com/domain/ProductTest.java
Labels: refactor, BE

#57 [BE] 배포 자동화 스크립트
  depoly.sh
Labels: BE, Depoly

#58 [FE} 캐러셀 컴포넌트 구현
  FE/.env
  FE/src/Pages/Main/index.jsx
  FE/src/components/BestMealContainer/index.jsx
  FE/src/components/Carousel/index.jsx
  FE/src/components/Carousel/style.js
  FE/src/components/MealCard/style.js
  FE/src/components/MealContainer/index.jsx
  FE/src/constants/index.js
Labels: feat, FE

#59 [FE] Custom Axios 작성 및 데이터 fetch 기능
  FE/.env
  FE/package-lock.json
  FE/src/Pages/Main/index.jsx
  FE/src/Pages/Main/style.js
  FE/src/components/BestMealCard/index.jsx
  FE/src/components/BestMealContainer/index.jsx
  FE/src/components/BestMealContainer/style.js
  FE/src/components/Header/index.jsx
  FE/src/components/Header/style.js
  FE/src/components/MealCard/index.jsx
  FE/src/components/MealContainer/index.jsx
  FE/src/constants/index.js
  FE/src/hooks/useAxios.js
  FE/src/index.js
Labels: feat, FE

#60 [BE] Github 로그인/로그아웃 기능
  BE/src/main/java/sidedish/com/config/GitHubOAuthUtils.java
  BE/src/main/java/sidedish/com/config/WebConfig.java
  BE/src/main/java/sidedish/com/controller/DomainDtoMapper.java
  BE/src/main/java/sidedish/com/controller/LoginController.java
  BE/src/main/java/sidedish/com/controller/model/UserResponse.java
  BE/src/main/java/sidedish/com/domain/GitHubAccessToken.java
  BE/src/main/java/sidedish/com/domain/User.java
  BE/src/main/java/sidedish/com/interceptor/LoginInterceptor.java
  BE/src/main/java/sidedish/com/repository/UserRepository.java
  BE/src/main/java/sidedish/com/service/LoginService.java
  BE/src/main/resources/db/schema.sql
  BE/src/test/resources/testdb/schema.sql
Labels: common, feat, BE

#63 [FE] Deatil 페이지 및 OAuth 테스트용 뷰 추가
  FE/public/index.html
  FE/src/App.jsx
  FE/src/Pages/Main/index.jsx
  FE/src/components/BestMealContainer/index.jsx
  FE/src/components/Carousel/index.jsx
  FE/src/components/Carousel/style.js
  FE/src/components/DetailModal/index.jsx
  FE/src/components/DetailModal/style.js
  FE/src/components/Header/index.jsx
  FE/src/components/Header/style.js
  FE/src/components/MealCard/index.jsx
  FE/src/components/MealCard/style.js
  FE/src/components/MealContainer/index.jsx
  FE/src/components/Portal/index.jsx
  FE/src/components/Portal/style.js
  FE/src/hooks/useAxios.js
  FE/src/styles/GlobalStyle.jsx
  FE/src/utils/index.js
Labels: feat, FE
